export const projects = [
  {
    slug: 'leadmate-ai-sales-assistant',
    title: 'Leadmate AI Sales Assistant',
    category: 'AI Sales Platform',
    desc: 'An AI-powered sales assistant that helps teams organize, qualify, and act on leads through automated workflows.',
    img: '/images/ecommerce.png',
    stack: ['Next.js', 'FastAPI', 'LLM APIs'],
    overview: 'Leadmate is an AI-powered sales assistant designed to help sales teams turn scattered lead activity into a clearer, more actionable workflow. The product combines structured lead management with intelligent, automated interactions.',
    role: 'Full-stack developer and product engineering collaborator',
    features: ['Lead organization and qualification', 'AI-assisted sales interactions', 'Action-focused workflow design', 'Scalable API architecture'],
    challenges: 'The main challenge was making AI-assisted workflows feel useful and predictable inside a business tool. The product needed clear states, practical automation, and a user experience that kept people in control.',
    outcome: 'A structured foundation for sales teams to manage leads more consistently while reducing repetitive manual follow-up work.',
  },
  {
    slug: 'health-insurance-system',
    title: 'Health Insurance System',
    category: 'Enterprise Software',
    desc: 'Role-based dashboards for managing employees, patients, administrators, and policy assignments.',
    img: '/images/pharma.png',
    stack: ['ASP.NET Core', 'MVC', 'SQL Server'],
    overview: 'A secure business application for coordinating insurance operations across employees, patients, administrators, and policy records through dedicated role-based dashboards.',
    role: 'Full-stack developer',
    features: ['Role-based access control', 'Employee and patient management', 'Policy assignment workflows', 'Administrative dashboards'],
    challenges: 'The system required clear separation between roles and reliable data flows across several operational areas. The interface had to remain approachable while supporting detailed administrative tasks.',
    outcome: 'A maintainable enterprise workflow that gives each user role the tools and visibility needed for day-to-day insurance operations.',
  },
  {
    slug: 'hotel-management-system',
    title: 'Hotel Management System',
    category: 'Full-stack Web App',
    desc: 'A complete operations platform for room bookings, employees, salaries, and role management.',
    img: '/images/management.png',
    stack: ['Next.js', 'Node.js', 'Express'],
    overview: 'A full-stack hotel operations platform that brings reservations, employees, salaries, and access management into one responsive experience.',
    role: 'Full-stack developer',
    features: ['Room booking management', 'Employee and salary records', 'Role and permission management', 'Responsive operational interface'],
    challenges: 'The challenge was connecting multiple hotel workflows without making the experience difficult to scan. The platform needed useful navigation and consistent data handling across desktop and mobile screens.',
    outcome: 'A practical management system that centralizes hotel administration and supports faster daily operations.',
  },
  {
    slug: 'e-commerce-platform',
    title: 'E-Commerce Platform',
    category: 'Commerce Experience',
    desc: 'A polished shopping experience with authentication, product discovery, and Stripe payments.',
    img: '/images/ecommerce.png',
    stack: ['React', 'Tailwind', 'Stripe'],
    overview: 'A conversion-focused ecommerce experience built around simple product discovery, authentication, and a reliable payment flow.',
    role: 'Full-stack developer',
    features: ['Product search and discovery', 'Authentication flow', 'New arrivals experience', 'Stripe payment integration'],
    challenges: 'The key challenge was balancing visual polish with a fast, frictionless shopping journey. Product browsing, account access, and checkout needed to feel like one coherent experience.',
    outcome: 'A clean commerce foundation designed to support customer trust, product exploration, and future catalog growth.',
  },
  {
    slug: 'agentos',
    title: 'AgentOS',
    category: 'Agentic AI Platform',
    desc: 'A multi-tenant platform for configuring, managing, and running AI agents with flexible model and voice integrations.',
    img: '/images/agentos.png',
    stack: ['Next.js', 'FastAPI', 'AI Agents'],
    overview: 'AgentOS is a multi-tenant AI Agent Management Platform built to make agent configuration, runtime selection, and voice-enabled workflows easier to manage.',
    role: 'AI platform developer',
    features: ['Multi-tenant agent configuration', 'Swappable LLM runtimes', 'Voice pipeline integration', 'Agent-as-a-Service architecture'],
    challenges: 'The platform needed to support different agent configurations without coupling every experience to one model provider. Clear boundaries between tenant settings, runtime behavior, and user-facing workflows were essential.',
    outcome: 'A flexible platform direction for teams that want to configure and operate AI agents with room for evolving model and voice capabilities.',
  },
];

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}
